# Generated by Django 4.2.5 on 2023-09-09 14:39

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservation_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='login_date',
            field=models.DateField(default=datetime.datetime.now, validators=[django.core.validators.MinValueValidator(datetime.datetime.today)]),
        ),
    ]
