# Generated by Django 4.2.5 on 2023-09-09 14:48

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_reservation_login_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='login_date',
            field=models.DateField(default=datetime.datetime.now, validators=[django.core.validators.MinValueValidator(datetime.date(2023, 9, 9))]),
        ),
    ]
